export const ENV_VARS = {
    EMAILJS_SERVICE_ID: import.meta.env.VITE_EMAILJS_SERVICE_ID,
    EMAILJS_TO_YOU_TEMPLATE_ID: import.meta.env.VITE_EMAILJS_TO_YOU_TEMPLATE_ID,
    EMAILJS_AUTO_REPLY_TEMPLATE_ID: import.meta.env.VITE_EMAILJS_AUTO_REPLY_TEMPLATE_ID,
    EMAILJS_PUBLIC_KEY: import.meta.env.VITE_EMAILJS_PUBLIC_KEY,
};